// LOGIN
export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"

// LOGOUT
export const LOGOUT_START = "LOGOUT_START"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAIL = "LOGOUT_FAIL"

// MESSAGES
export const CREATE_MESSAGE = "CREATE_MESSAGE"
export const CREATE_WARNING = "CREATE_WARNING"
