// LOGIN
export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"

// LOGOUT
export const LOGOUT_START = "LOGOUT_START"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAIL = "LOGOUT_FAIL"

// MESSAGES
export const CREATE_MESSAGE = "CREATE_MESSAGE"
export const CREATE_WARNING = "CREATE_WARNING"


export const REGISTER_FAIL = "REGISTER_FAIL"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"


// TODO
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS'
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL'

// TODO
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS'
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL'


export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";


export const UTILITY_START_SEVER_CALL = "UTILITY_START_SERVER_CALL";
// TODO
export const CART_INCREMENT_ITEM_SUCCESS = 'CART_INCREMENT_ITEM_SUCCESS'
export const CART_INCREMENT_ITEM_FAIL = 'CART_INCREMENT_ITEM_FAIL'



export const CART_DECREMENT_ITEM_SUCCESS = 'CART_DECREMENT_ITEM_SUCCESS'
export const CART_DECREMENT_ITEM_FAIL = 'CART_DECREMENT_ITEM_FAIL'



export const CART_CLEAN_CART_SUCCESS = 'CART_CLEAN_CART_SUCCESS'
export const CART_CLEAN_CART_FAIL = 'CART_CLEAN_CART_FAIL'

export const CART_CLEAN_ITEM_SUCCESS = 'CART_CLEAN_ITEM_SUCCESS';
export const CART_CLEAN_ITEM_FAIL = 'CART_CLEAN_ITEM_FAIL';

export const CART_ADD_ITEM_SUCCESS = 'CART_ADD_ITEM_SUCCESS';
export const CART_ADD_ITEM_FAIL = 'CART_ADD_ITEM_FAIL'